parameters:
#    sekjun9878_invoice.example.class: sekjun9878\InvoiceBundle\Example

services:
#    sekjun9878_invoice.example:
#        class: %sekjun9878_invoice.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
