<?php

namespace sekjun9878\CakePanelBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Guzzle\Http\Client;

/**
 * ServerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServerRepository extends EntityRepository
{

}
